version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: "sudo npm install --safe"
      - run:
          name: Install Supertest
          command: "sudo npm install supertest -g"
      - run:
          name: Install Mocha
          command: "sudo npm install mocha -g"
      - run:
          name: Install Chai
          command: "sudo npm install chai -g"
      - run:
          name: Install Joi          
          command: "sudo npm install joi -g"
      - run:
          name: Install Mochawesome
          command: "sudo npm install --save-dev mochawesome -g"
      - run:
          name: Install Faker
          command: "sudo npm install @faker-js/faker -g"
      - run:
          name: Test
          command: "npm run exec_test"
